// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBfvEtrre0x1efB8zWczA91TqV6h3OUBw',
    appId: '1:932149870346:web:e7f7b86e549001bbd384f3',
    messagingSenderId: '932149870346',
    projectId: 'booktrack-db',
    authDomain: 'booktrack-db.firebaseapp.com',
    storageBucket: 'booktrack-db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiRUG0NItiJOHQrGRGlOpd0FHAicOJn8Y',
    appId: '1:932149870346:android:d1b04309756889bfd384f3',
    messagingSenderId: '932149870346',
    projectId: 'booktrack-db',
    storageBucket: 'booktrack-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFuQEpxzGNruK4tOKko1p2R-tBUfI34_0',
    appId: '1:932149870346:ios:e0d81394c09d322ed384f3',
    messagingSenderId: '932149870346',
    projectId: 'booktrack-db',
    storageBucket: 'booktrack-db.firebasestorage.app',
    iosBundleId: 'com.example.booktrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBfvEtrre0x1efB8zWczA91TqV6h3OUBw',
    appId: '1:932149870346:web:779fcba52401f426d384f3',
    messagingSenderId: '932149870346',
    projectId: 'booktrack-db',
    authDomain: 'booktrack-db.firebaseapp.com',
    storageBucket: 'booktrack-db.firebasestorage.app',
  );
}
